/*
 * @Date         : 2024-07-19 17:14:40 星期5
 * @Author       : xut
 * @Description  :
 */
import process from "node:process"

console.log("Nodejs Version: ", process.version) // Nodejs Version:  v22.2.0
console.log("Nodejs dependency library version: ", process.versions)
// Nodejs dependency library version:  {
//   node: '22.2.0',
//   acorn: '8.11.3',
//   ada: '2.7.8',
//   ares: '1.28.1',
//   base64: '0.5.2',
//   brotli: '1.1.0',
//   cjs_module_lexer: '1.2.2',
//   cldr: '45.0',
//   icu: '75.1',
//   llhttp: '9.2.1',
//   modules: '127',
//   napi: '9',
//   nghttp2: '1.61.0',
//   nghttp3: '0.7.0',
//   ngtcp2: '1.3.0',
//   openssl: '3.0.13+quic',
//   simdjson: '3.9.2',
//   simdutf: '5.2.8',
//   tz: '2024a',
//   undici: '6.13.0',
//   unicode: '15.1',
//   uv: '1.48.0',
//   uvwasi: '0.0.21',
//   v8: '12.4.254.14-node.12',
//   zlib: '1.3.0.1-motley-7d77fb7'
// }
console.log("Nodejs release: ", process.release)
// Nodejs release:  {
//   name: 'node',
//   sourceUrl: 'https://nodejs.org/download/release/v22.2.0/node-v22.2.0.tar.gz',
//   headersUrl: 'https://nodejs.org/download/release/v22.2.0/node-v22.2.0-headers.tar.gz',
//   libUrl: 'https://nodejs.org/download/release/v22.2.0/win-x64/node.lib'
// }
console.log("Nodejs config: ", process.config)
// Nodejs config:  {
//   target_defaults: {
//     cflags: [],
//     default_configuration: 'Release',
//     defines: [
//       'NODE_OPENSSL_CONF_NAME=nodejs_conf',
//       'NODE_OPENSSL_HAS_QUIC',
//       'ICU_NO_USER_DATA_OVERRIDE'
//     ],
//     include_dirs: [],
//     libraries: []
//   },
//   variables: {
//     asan: 0,
//     clang: 0,
//     coverage: false,
//     dcheck_always_on: 0,
//     debug_nghttp2: false,
//     debug_node: false,
//     enable_lto: false,
//     enable_pgo_generate: false,
//     enable_pgo_use: false,
//     error_on_warn: false,
//     force_dynamic_crt: 0,
//     host_arch: 'x64',
//     icu_data_in: '..\\..\\deps\\icu-tmp\\icudt75l.dat',
//     icu_endianness: 'l',
//     icu_gyp_path: 'tools/icu/icu-generic.gyp',
//     icu_path: 'deps/icu-small',
//     icu_small: false,
//     icu_ver_major: '75',
//     is_debug: 0,
//     libdir: 'lib',
//     llvm_version: '0.0',
//     napi_build_version: '9',
//     nasm_version: '2.16',
//     node_builtin_shareable_builtins: [
//       'deps/cjs-module-lexer/lexer.js',
//       'deps/cjs-module-lexer/dist/lexer.js',
//       'deps/undici/undici.js'
//     ],
//     node_byteorder: 'little',
//     node_debug_lib: false,
//     node_enable_d8: false,
//     node_enable_v8_vtunejit: false,
//     node_fipsinstall: false,
//     node_install_corepack: true,
//     node_install_npm: true,
//     node_library_files: [
//       'lib/_http_agent.js',
//       'lib/_http_client.js',
//       'lib/_http_common.js',
//       'lib/_http_incoming.js',
//       'lib/_http_outgoing.js',
//       'lib/_http_server.js',
//       'lib/_stream_duplex.js',
//       'lib/_stream_passthrough.js',
//       'lib/_stream_readable.js',
//       'lib/_stream_transform.js',
//       'lib/_stream_wrap.js',
//       'lib/_stream_writable.js',
//       'lib/_tls_common.js',
//       'lib/_tls_wrap.js',
//       'lib/assert.js',
//       'lib/assert/strict.js',
//       'lib/async_hooks.js',
//       'lib/buffer.js',
//       'lib/child_process.js',
//       'lib/cluster.js',
//       'lib/console.js',
//       'lib/constants.js',
//       'lib/crypto.js',
//       'lib/dgram.js',
//       'lib/diagnostics_channel.js',
//       'lib/dns.js',
//       'lib/dns/promises.js',
//       'lib/domain.js',
//       'lib/events.js',
//       'lib/fs.js',
//       'lib/fs/promises.js',
//       'lib/http.js',
//       'lib/http2.js',
//       'lib/https.js',
//       'lib/inspector.js',
//       'lib/inspector/promises.js',
//       'lib/internal/abort_controller.js',
//       'lib/internal/assert.js',
//       'lib/internal/assert/assertion_error.js',
//       'lib/internal/assert/calltracker.js',
//       'lib/internal/async_hooks.js',
//       'lib/internal/blob.js',
//       'lib/internal/blocklist.js',
//       'lib/internal/bootstrap/node.js',
//       'lib/internal/bootstrap/realm.js',
//       'lib/internal/bootstrap/shadow_realm.js',
//       'lib/internal/bootstrap/switches/does_not_own_process_state.js',
//       'lib/internal/bootstrap/switches/does_own_process_state.js',
//       'lib/internal/bootstrap/switches/is_main_thread.js',
//       'lib/internal/bootstrap/switches/is_not_main_thread.js',
//       'lib/internal/bootstrap/web/exposed-wildcard.js',
//       'lib/internal/bootstrap/web/exposed-window-or-worker.js',
//       'lib/internal/buffer.js',
//       'lib/internal/child_process.js',
//       'lib/internal/child_process/serialization.js',
//       'lib/internal/cli_table.js',
//       'lib/internal/cluster/child.js',
//       'lib/internal/cluster/primary.js',
//       'lib/internal/cluster/round_robin_handle.js',
//       'lib/internal/cluster/shared_handle.js',
//       'lib/internal/cluster/utils.js',
//       'lib/internal/cluster/worker.js',
//       'lib/internal/console/constructor.js',
//       'lib/internal/console/global.js',
//       'lib/internal/constants.js',
//       'lib/internal/crypto/aes.js',
//       'lib/internal/crypto/certificate.js',
//       'lib/internal/crypto/cfrg.js',
//       'lib/internal/crypto/cipher.js',
//       'lib/internal/crypto/diffiehellman.js',
//       'lib/internal/crypto/ec.js',
//       'lib/internal/crypto/hash.js',
//       'lib/internal/crypto/hashnames.js',
//       'lib/internal/crypto/hkdf.js',
//       'lib/internal/crypto/keygen.js',
//       'lib/internal/crypto/keys.js',
//       'lib/internal/crypto/mac.js',
//       'lib/internal/crypto/pbkdf2.js',
//       'lib/internal/crypto/random.js',
//       'lib/internal/crypto/rsa.js',
//       'lib/internal/crypto/scrypt.js',
//       'lib/internal/crypto/sig.js',
//       'lib/internal/crypto/util.js',
//       'lib/internal/crypto/webcrypto.js',
//       'lib/internal/crypto/webidl.js',
//       'lib/internal/crypto/x509.js',
//       'lib/internal/debugger/inspect.js',
//       'lib/internal/debugger/inspect_client.js',
//       'lib/internal/debugger/inspect_repl.js',
//       'lib/internal/dgram.js',
//       'lib/internal/dns/callback_resolver.js',
//       'lib/internal/dns/promises.js',
//       'lib/internal/dns/utils.js',
//       'lib/internal/encoding.js',
//       'lib/internal/error_serdes.js',
//       'lib/internal/errors.js',
//       'lib/internal/event_target.js',
//       'lib/internal/events/abort_listener.js',
//       'lib/internal/events/symbols.js',
//       'lib/internal/file.js',
//       ... 212 more items
//     ],
//     node_module_version: 127,
//     node_no_browser_globals: false,
//     node_prefix: '\\usr\\local',
//     node_release_urlbase: 'https://nodejs.org/download/release/',
//     node_shared: false,
//     node_shared_ada: false,
//     node_shared_brotli: false,
//     node_shared_cares: false,
//     node_shared_http_parser: false,
//     node_shared_libuv: false,
//     node_shared_nghttp2: false,
//     node_shared_nghttp3: false,
//     node_shared_ngtcp2: false,
//     node_shared_openssl: false,
//     node_shared_simdjson: false,
//     node_shared_simdutf: false,
//     node_shared_uvwasi: false,
//     node_shared_zlib: false,
//     node_tag: '',
//     node_target_type: 'executable',
//     node_use_bundled_v8: true,
//     node_use_node_code_cache: true,
//     node_use_node_snapshot: true,
//     node_use_openssl: true,
//     node_use_v8_platform: true,
//     node_with_ltcg: true,
//     node_without_node_options: false,
//     node_write_snapshot_as_array_literals: true,
//     openssl_is_fips: false,
//     openssl_quic: true,
//     ossfuzz: false,
//     shlib_suffix: 'so.127',
//     single_executable_application: true,
//     target_arch: 'x64',
//     ubsan: 0,
//     use_prefix_to_find_headers: false,
//     v8_enable_31bit_smis_on_64bit_arch: 0,
//     v8_enable_extensible_ro_snapshot: 0,
//     v8_enable_gdbjit: 0,
//     v8_enable_hugepage: 0,
//     v8_enable_i18n_support: 1,
//     v8_enable_inspector: 1,
//     v8_enable_javascript_promise_hooks: 1,
//     v8_enable_lite_mode: 0,
//     v8_enable_maglev: 1,
//     v8_enable_object_print: 1,
//     v8_enable_pointer_compression: 0,
//     v8_enable_shared_ro_heap: 1,
//     v8_enable_short_builtin_calls: 1,
//     v8_enable_v8_checks: 0,
//     v8_enable_webassembly: 1,
//     v8_no_strict_aliasing: 1,
//     v8_optimized_debug: 1,
//     v8_promise_internal_field_count: 1,
//     v8_random_seed: 0,
//     v8_trace_maps: 0,
//     v8_use_siphash: 1,
//     want_separate_host_toolset: 0
//   }
// }
