# subject 主体（被访问的实体）
# object 对象（被访问的资源）
# action 动作（访问方式）
# domain 域或组
[request_definition]
# 定义了e.Enforce(args)函数中对应的参数
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
# g 代是一种 RBAC 模型，如 RBAC0，用户和角色的关系。
# 当在匹配器中使用时 g(r.sub, p.sub) 意味着请求中的 sub 应该在策略中拥有角色 user。
g = _, _

[policy_effect]
# 这是固定的，内置可选的策略有：
# 1. some(where (p.eft == allow)) 如果有匹配到一条 allow策略规则，最终效果是allow（也称为允许覆盖）
# 2. !some(where (p.eft == deny)) 如果没有匹配的deny策略规则，最终的效果是allow（也称为deny-override）
# 3. some(where (p.eft == allow)) && !some(where (p.eft == deny)) 必须至少有一个匹配的allow策略规则，并且不能有任何匹配的deny策略规则。 因此，以这种方式，支持允许和拒绝授权，并且拒绝优先。
# 4. priority(p.eft) || deny
# 5. subjectPriority(p.eft)
e = some(where (p.eft == allow))

[matchers]
# [匹配器]是策略匹配器的定义。 匹配器是定义如何根据请求评估策略规则的表达式。
# 表达式的顺序可以极大地影响性能。
# 支持唯一一个带有文本名称的运算符 in，检查右侧的数组，看是否包含等于左侧值的值，比如 m = r.sub.name in (r.obj.admins)
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && r.emthod == p.act || r.sub == "root"